Fix for valgrind error in msdffimp.cxx
Error: Conditional jump or move depends on uninitialised value(s)
Fix: Ensure that nGroupShapeFlags is initialized in the constructor
Also cleaned up some duplicate variables
(cherry picked from commit eb1d986b424a07a32dcc07e854e2b078150a3396)

Conflicts:

	filter/source/msfilter/msdffimp.cxx